image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf
  script:
    - make
  artifacts:
    paths:
      - unilink-select
    cache:
      paths:
        - "*.o"
